#!/usr/bin/python

from defs import *

def xLine(x):
   r = strRange(x)
   return """
voice%d.ly: xtemplate.py
	python xtemplate.py

voice%d.pdf: header.ly melodies%s.ly lyrics%d.ly voice%d.ly
	lilypond voice%d.ly
""" % (x, x, r, x, x, x)

def yLine(x):
   r = strRange(4 * x)
   lyrics = ""
   for i in xrange(4 * x - 3, 4 * x + 1):
      lyrics += " lyrics%d.ly" % i
   return """
voices%s.ly: ytemplate.py
	python ytemplate.py

voices%s.pdf: header.ly melodies%s.ly%s voices%s.ly
	lilypond voices%s.ly
""" % (r, r, r, lyrics, r, r)


def zLine():
   melodies = ""
   for i in xrange(1, 4):
      melodies += " melodies%s.ly" % strRange(4 * i)
   lyrics = ""
   for i in xrange(1, 13):
      lyrics += " lyrics%d.ly" % i
   return """
magnificat.ly: ztemplate.py
	python ztemplate.py

magnificat.pdf: header.ly%s%s magnificat.ly
	lilypond magnificat.ly

magnificat.midi: magnificat.pdf

magnificat.wav: magnificat.midi
	timidity magnificat.midi -Ow -omagnificat.wav >> /dev/null

""" % (melodies, lyrics)



file = open('Makefile', 'w')
file.write("\n# file automatically generated by ./build.py\n\n")

# all
file.write("all:")
for i in xrange(1, 13):
   file.write(" voice%d.pdf" % i)
for i in xrange(1, 4):
   file.write(" voices%s.pdf" % strRange(4 * i))
file.write(" magnificat.pdf magnificat.wav\n\n")


# x
for i in xrange(1, 13):
   file.write(xLine(i))

# y
for i in xrange(1, 4):
   file.write(yLine(i))

# z
file.write(zLine())

file.close()





