#!/usr/bin/python

from defs import *

def content(x):
   r = strRange(x) 
   l = numToLetter(x)
   return """
%c file automatically generated by ./xtemplate.py

\\include "header.ly"
\\include "melodies%s.ly"
\\include "lyrics%d.ly"

\header {
   piece = "Voice %d of 12"
}

\score {
   <<
    \\new Staff { \\new Voice = "voice%s" \\global \\voice%s  }
    \\new Lyrics \\lyricsto voice%s { \\lyrics%s }
   >>
   \\layout{}
   \\midi{}
}
""" % ('%', r, x, x, l, l, l, l)

for i in xrange(1, 13):
   file = open('voice' + str(i) + '.ly', 'w')
   file.write(content(i))
   file.close()




