#!/usr/bin/python

from defs import *

def content():
   inclMelodies = ""
   for i in xrange(1, 4):
      inclMelodies += '\\include "melodies%s.ly"\n' % strRange(4 * i)   
   inclLyrics = ""
   for i in xrange(1, 13):
      inclLyrics += '\\include "lyrics%d.ly"\n' % i
   staves = ""
   for j in xrange(1,4):
     staves += "\n   \\new ChoirStaff << "
     for i in xrange(4 * j - 3, 4 * j + 1):
        l = numToLetter(i)
        staves += """
      \\new Staff { \\new Voice = "voice%s" \\global \\voice%s  }
      \\new Lyrics \\lyricsto voice%s { \\lyrics%s }""" % (l, l, l, l)
     staves += "\n  >>"
   return """
%c file automatically generated by ./ztemplate.py

\\include "header.ly"
%s
%s

#(set-default-paper-size "a3" 'landscape)

\\score{
  << %s
  >>
   \\layout{}
   \\midi{}
}
""" % ('%', inclMelodies, inclLyrics, staves)


file = open('magnificat.ly', 'w')
file.write(content())
file.close()




